### ISSUE TITLE
Repackage for python3.7

### ISSUE THREAD

**Issue by rkevin-arch** [conda-forge/opty-feedstock#13]
We should repackage this for python3.7 and maybe 3.8. The package was last updated 2 years ago before python3.7 is a thing, so there is no `.tar.bz2` package on [conda-forge's file list](https://anaconda.org/conda-forge/opty/files) for python3.7, and so it can't be installed with python3.7.

**Comment by moorepants** [comment]
FYI I'm getting build errors with the latest Cython and SymPy so opty needs a bit of work to run on the latest dependencies. The main repo is here: https://github.com/csu-hmc/opty. I spent some time on it this month but didn't solve the issues.

**Comment by moorepants** [comment]
Fixed in #15.
